#!/usr/bin/env python3
import os
from datetime import date

# Paths
projects = {
    "Olodumare": ["client.gd", "server.gd", "websocket/WebSocketClient.gd", "websocket/WebSocketServer.gd"],
    "Exu": ["client.gd", "server.gd", "websocket/WebSocketClient.gd", "websocket/WebSocketServer.gd"]
}
base_dir = os.getcwd()
output_file = os.path.join(base_dir, "all_scripts_combined.txt")
readme_file = os.path.join(base_dir, "README.md")
combined_file_name = "all_scripts_combined.txt"

# Helper: convert header to GitHub anchor link
def anchor_from_header(header):
    # GitHub anchors: lowercase, spaces to "-", remove special chars except "-"
    import re
    anchor = header.lower()
    anchor = re.sub(r"[^\w\s-]", "", anchor)
    anchor = anchor.replace(" ", "-")
    return anchor

# Generate Table of Contents (with links to txt file)
def generate_toc():
    toc_lines = []
    idx = 1
    for proj, scripts in projects.items():
        for s in scripts:
            header_text = f"{proj}/{s}"
            anchor = anchor_from_header(f"Script {idx}: {header_text}")
            toc_lines.append(f"{idx}. [{header_text}]({combined_file_name}#{anchor})")
            idx += 1
    return toc_lines

# Update README with badge + TOC
def update_readme(readme_path):
    badge_line = f"![All Scripts Combined](https://img.shields.io/badge/All%20Scripts%20Combined-Last%20Generated%20{date.today().isoformat()}-blue)\n\n"
    toc_lines = generate_toc()
    toc_text = "### Table of Contents\n" + "\n".join(f"- {line}" for line in toc_lines) + "\n\n"

    if not os.path.exists(readme_path):
        with open(readme_path, "w") as f:
            f.write(badge_line + toc_text)
        return

    with open(readme_path, "r") as f:
        lines = f.readlines()

    # Remove old badge and TOC (if any)
    new_lines = []
    skip = False
    for line in lines:
        if line.startswith("![All Scripts Combined]"):
            skip = True
            continue
        if skip and line.strip().startswith("### Table of Contents"):
            skip = False
            while line.strip() != "" and "Table of Contents" not in line:
                line = next(iter(lines), "")
            continue
        new_lines.append(line)

    # Insert new badge + TOC at the top
    with open(readme_path, "w") as f:
        f.write(badge_line)
        f.write(toc_text)
        f.writelines(new_lines)

# Generate combined scripts file
def generate_combined_file(output_path):
    toc_lines = generate_toc()
    with open(output_path, "w") as out_f:
        out_f.write(f"Generated by: python3 {os.path.basename(__file__)}\n")
        out_f.write("=" * 80 + "\n\n")
        out_f.write("Table of Contents\n")
        for line in toc_lines:
            # Strip link part for txt file TOC
            out_f.write(" ".join(line.split("]")[0].split(" ")[1:]) + "\n")
        out_f.write("\n" + "=" * 80 + "\n\n")

        idx = 1
        for proj, scripts in projects.items():
            for s in scripts:
                path = os.path.join(base_dir, proj, s)
                out_f.write(f"Project: {proj}\n")
                out_f.write(f"Script {idx}: {proj}/{s}\n")
                out_f.write("-" * 60 + "\n")
                if os.path.exists(path):
                    with open(path, "r") as script_f:
                        out_f.write(script_f.read() + "\n")
                else:
                    out_f.write("# File not found\n\n")
                out_f.write("=" * 80 + "\n\n")
                idx += 1

if __name__ == "__main__":
    generate_combined_file(output_file)
    update_readme(readme_file)
    print(f"Combined scripts written to {output_file} and README updated with badge + clickable TOC.")
