#!/usr/bin/env python3
"""
Generate a combined text file of all Godot scripts in Olodumare and Exu projects.

Usage:
    python3 generate_all_scripts.py
"""

import os

# Projects to include
projects = ["Olodumare", "Exu"]
output_file = "all_scripts_combined.txt"

# Command used to generate this file
command_line_note = "Generated by: python3 generate_all_scripts.py\n"

# Start writing the output
with open(output_file, "w", encoding="utf-8") as out_f:
    # Write command line note at top
    out_f.write(command_line_note)
    out_f.write("="*80 + "\n\n")

    # Table of contents
    out_f.write("Table of Contents\n")
    toc = []
    
    for project in projects:
        for root, dirs, files in os.walk(project):
            for file in files:
                if file.endswith(".gd"):
                    rel_path = os.path.relpath(os.path.join(root, file), ".")
                    toc.append(rel_path)
    
    for i, file_path in enumerate(toc, 1):
        out_f.write(f"{i}. {file_path}\n")
    
    out_f.write("\n" + "="*80 + "\n\n")

    # Write all scripts sequentially
    for i, file_path in enumerate(toc, 1):
        out_f.write(f"Project: {file_path.split(os.sep)[0]}\n")
        out_f.write(f"Script {i}: {file_path}\n")
        out_f.write("-"*60 + "\n")
        with open(file_path, "r", encoding="utf-8") as f:
            out_f.write(f.read())
        out_f.write("\n\n" + "="*80 + "\n\n")

print(f"All scripts combined into {output_file}")
